### ISSUE TITLE
Is have docker with all dependencies?

### ISSUE THREAD

**Issue by faranaziz** [Tencent/Forward#17]
Thanks you

**Comment by yuanzexi** [comment]
@faranaziz   Sorry for lack of docker currently. We'll try to provide it later. 
Actually, because Forward only depends on TensorRT, CUDA and Torch/Tensorflow, We think **Docker provided by [TensorRT Github](https://github.com/NVIDIA/TensorRT) is enough for you to test Forward**. You could try to use the Docker provided by [TensorRT](https://github.com/NVIDIA/TensorRT).
