### ISSUE TITLE
not find:aten::gelu 

### ISSUE THREAD

**Issue by Fan9** [Tencent/Forward#6]
There is no problem with my environment and run demo.
 But when using bert ,I encounter a bug. Do I need to implement aten::gelu by myself?

```

The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
[ERROR] 2021-04-01 22:03:55,866 torch_desc_manager.cpp(128): Could not find layer create for node aten::gelu: output input.4
[ERROR] 2021-04-01 22:03:55,866 torch_engine.cpp(235): Parse torch module failed
Traceback (most recent call last):
  File "tensorrt_forward.py", line 48, in <module>
    outputs = engine.forward_with_name(dummy_inputs)
AttributeError: 'NoneType' object has no attribute 'forward_with_name
```

**Comment by yuanzexi** [comment]
This problem is possibly caused by unsupported variant BERT model. Forward only support standard bert model, and it will recognized the combination of operations as a transformer pattern. `aten::gelu` should be included in the pattern of transformer layers. So here Forward failed to recognized your BERT model and threw a error.

**Comment by Fan9** [comment]
ok, Thank you for your reply！
